import json
from typing import Any
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.api.deps import get_current_user
from app.models.models import User, Course, Chapter, DifficultyLevel
from app.schemas.course import CourseGenerateRequest, CourseGenerateResponse, ChapterSchema
from app.agents.curriculum_agent import generate_course_syllabus

router = APIRouter()


@router.post("/generate", response_model=CourseGenerateResponse, status_code=status.HTTP_201_CREATED)
def generate_course(
    *,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    req: CourseGenerateRequest,
) -> Any:
    """
    Generate a complete AI course from a topic string using Gemini.
    Requires authentication (JWT token in Authorization header).
    """
    try:
        # Call the Gemini Curriculum Agent
        course_data = generate_course_syllabus(req.topic, req.difficulty)
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail=f"AI generation failed. Please try again. Error: {str(e)}"
        )

    # Map difficulty string to our enum
    difficulty_map = {
        "starter": DifficultyLevel.STARTER,
        "intermediate": DifficultyLevel.INTERMEDIATE,
        "advanced": DifficultyLevel.ADVANCED,
    }
    difficulty_enum = difficulty_map.get(req.difficulty, DifficultyLevel.STARTER)

    # Save Course to database
    db_course = Course(
        title=course_data.get("title", req.topic),
        description=course_data.get("description", ""),
        source_type="text",
        status="ready",
        difficulty=difficulty_enum,
        owner_id=current_user.id,
    )
    db.add(db_course)
    db.flush()  # flush to get the new course id before adding chapters

    # Save each Chapter to database
    chapters_out = []
    for ch in course_data.get("chapters", []):
        db_chapter = Chapter(
            course_id=db_course.id,
            order=ch.get("order", 0),
            title=ch.get("title", ""),
            objective=ch.get("objective", ""),
            key_concepts=json.dumps(ch.get("key_concepts", [])),
            content_summary=ch.get("content_summary", ""),
        )
        db.add(db_chapter)
        chapters_out.append(ChapterSchema(
            order=db_chapter.order,
            title=db_chapter.title,
            objective=db_chapter.objective,
            key_concepts=ch.get("key_concepts", []),
            content_summary=db_chapter.content_summary,
        ))

    db.commit()
    db.refresh(db_course)

    return CourseGenerateResponse(
        id=db_course.id,
        title=db_course.title,
        description=db_course.description,
        difficulty=req.difficulty,
        status=db_course.status,
        chapters=chapters_out,
    )


@router.get("/my-courses")
def get_my_courses(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return all courses generated by the authenticated user."""
    courses = db.query(Course).filter(Course.owner_id == current_user.id).all()
    return [{"id": c.id, "title": c.title, "description": c.description,
             "difficulty": c.difficulty, "status": c.status, "created_at": c.created_at} for c in courses]
